name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v .

    - name: Build amd64
    # Build statically linked so we can use it in a from scratch dockerfile
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' 

    - name: Build and Push Docker amd64
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: moztr/tc4400_exporter
        tags: ${{ GITHUB_SHA }}-amd64

    - name: Build arm64
    # Build statically linked so we can use it in a from scratch dockerfile
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -tags netgo -ldflags '-w' 

    - name: Build and Push Docker arm64
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: moztr/tc4400_exporter
        tags: ${{ GITHUB_SHA }}-arm64v8

    - name: Build arm
    # Build statically linked so we can use it in a from scratch dockerfile
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -a -tags netgo -ldflags '-w' 

    - name: Build and Push Docker arm
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: moztr/tc4400_exporter
        tags: ${{ GITHUB_SHA }}-arm32

    - name: Multi Arch manifest
      run: 
        - export DOCKER_CLI_EXPERIMENTAL=enabled 
        - echo ${{ secrets.DOCKER_USERNAME }} | docker login -u ${{ secrets.DOCKER_PASSWORD }} --password-stdin
        - docker manifest create moztr/tc4400_exporter:${{ GITHUB_SHA }} moztr/tc4400_exporter:${{ GITHUB_SHA }}-amd64 moztr/tc4400_exporter:${{ GITHUB_SHA }}-arm64v8 moztr/tc4400_exporter:${{ GITHUB_SHA }}-arm32
        - docker manifest annotate moztr/tc4400_exporter:${{ GITHUB_SHA }} moztr/tc4400_exporter:${{ GITHUB_SHA }}-arm32 --os linux --arch arm --variant v6
        - docker manifest annotate moztr/tc4400_exporter:${{ GITHUB_SHA }} moztr/tc4400_exporter:${{ GITHUB_SHA }}-arm32 --os linux --arch arm --variant v7
        - docker manifest annotate moztr/tc4400_exporter:${{ GITHUB_SHA }} moztr/tc4400_exporter:${{ GITHUB_SHA }}-arm64v8 --os linux --arch arm64 --variant v8
        - docker manifest push --purge moztr/tc4400_exporter:${{ GITHUB_SHA }}
