name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
    # Build statically linked so we can use it in a from scratch dockerfile
      run: CGO_ENABLED=0 GOOS=linux go build -a -tags netgo -ldflags '-w' 

    - name: Test
      run: go test -v .
    
    - name: Build and Push Docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: moztr/tc4400_exporter
        tags: latest
